config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :artists do
    resources :songs
  end

  namespace :api do
    resources :artists do
      resources :songs
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }, uniqueness: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :name, presence: true, length: { maximum: 250 }

end

app/controllers/api/artists_controller.rb
# class Api::ArtistsController < ApplicationController
#   skip_before_action :verify_authenticity_token
#
#   def index
#     artists = Artist.all
#     render status: 200, json: artists
#   end
#
#   def show
#     artist = Artist.find(params[:id])
#     photos = artist.photos
#
#     render status: 200, json: artist
#   end
#
#   def create
#     artist = Artist.new(artist_params)
#
#     if artist.save
#       render status: 201, json: artist
#     else
#       render status: 422, json: {
#         errors: artist.errors
#       }.to_json
#     end
#   end
#
#   def destroy
#     artist = Artist.find(params[:id])
#     artist.destroy
#
#     render status: 200, json: {
#     }.to_json
#   end
#
#   def update
#     artist = Artist.find(params[:id])
#       if artist.update(artist_params)
#         render status: 200, json: {
#           artist: artist
#         }.to_json
#       else
#          render status: 422, json: {
#           errors: artist.errors
#         }.to_json
#       end
#   end
#
#   private
#   def artist_params
#     params.require(:artist).permit(:name)
#   end
#
# end

app/controllers/api/songs_controller.rb
skip_before_action :verify_authenticity_token

before_action :artist_set

  def new
    @song = @artist.songs.build
  end

  def create
    @song = @artist.songs.create(song_params)
    if @song.save
      render status: 200, json: @song
    else
      render status: 422, json: {
        errors: @song.errors
      }
    end
  end

  def destroy
    @song = @artist.songs.find(params[:id])
    @song.destroy
    render status: 200, json: {
      message: "Song deleted"
    }.to_json
  end

  private

  def artist_set
    @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:id, :name)
  end

app/controllers/api/welcome_controller.rb
skip_before_action :verify_authenticity_token

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end
  end

  def update
  @artist = Artist.find(params[:id])

  if @artist.update(artist_params)
    redirect_to @artist
  else
    render 'edit'
  end
end

def destroy
  @artist = Artist.find(params[:id])
  @artist.destroy

  redirect_to root_path
end

  private
  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
    @song.destroy
    redirect_to artist_path(@artist)
  end

  private
  def song_params
      params.require(:song).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_form.html.erb
<%= form_with model: @artist, local: true do |form| %>

<% if @artist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@artist.errors.count, "error") %> prohibited
      this artist from being saved:
    </h2>
    <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Codaisseurify</h1>
<hr>
<%= link_to 'New artist', new_artist_path %>
<hr>
<table>
  <tr>
    <th></th>
  </tr>

  <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.name, artist_path(artist)%></td>
      <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
      <td><%= link_to 'Destroy', artist_path(artist),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h1>
  <%= @artist.name %>
</h1>
<hr>
<% @artist.photos.each do |photo| %>
  <%= image_tag photo.image.thumbnail %>
<% end %>

<h4>Songs in database</h4>
<%= render @artist.songs %>

<h4>Add a song:</h4>
<%= render 'songs/form' %>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurifyfive</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: [ @artist, @artist.songs.build ]) do |form| %>
  <p>

    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/songs/_song.html.erb
<p>
  <%= song.name %>
  <%= link_to 'Delete Song', [song.artist, song],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

</p>

app/views/welcome/index.html.erb
<h1>Welcome to Codaisseurify!</h1>
<%= link_to 'All the artists', controller: 'artists' %>